#include<stdio.h>
void main()
{
	printf("\t\t\t\t\t\t\t**\t\t\t\t\t\t\t\n\n\n");
	printf("\t\t\t\t\t\t**\t**\t**\t\t\t\t\t\t\n\n\n");
	printf("\t\t\t\t\t***\t\t**\t\t**\t\t\t\t\t\n\n\n");
	printf("\t\t\t\t**\t\t\t**\t\t\t**\t\t\t\t\n\n\n");
	printf("\t\t\t**\t\t\t\t**\t\t\t\t**\t\t\t\n\n\n");
	printf("\t\t**\t\t\t\t**\t**\t**\t\t\t\t**\t\t\n\n\n");
	printf("\t**\t\t\t**\t\t\t**\t\t\t**\t\t\t**\t\n\n\n");
	printf("**\t\t**\t\t\t\t\t***\t\t\t\t\t**\t\t**\n\n\n");
	printf("**\t\t\t\t\t\t\t**\t\t\t\t\t\t\t**\n\n\n");
	printf("\t**\t\t\t\t\t\t**\t\t\t\t\t\t**\t\n\n\n");
	printf("\t\t**\t\t\t\t\t**\t\t\t\t\t**\t\t\n\n\n");
	printf("\t\t\t**\t\t\t\t**\t\t\t\t**\t\t\t\n\n\n");
	printf("\t\t\t\t**\t\t\t**\t\t\t**\t\t\t\t\n\n\n");
	printf("\t\t\t\t\t**\t\t**\t\t**\t\t\t\t\t\n\n\n");
	printf("\t\t\t\t\t\t**\t**\t**\t\t\t\t\t\t\n\n\n");
	printf("\t\t\t\t\t\t\t**\t\t\t\t\t\t\t\n\n\n");
	printf("\t\t\t\t\t\t**\t**\t**\t\t\t\t\t\t\n\n\n");
	printf("\t\t\t\t\t**\t\t**\t\t***\t\t\t\t\t\n\n\n");
	printf("\t\t\t\t**\t\t**\t**\t**\t\t**\t\t\t\t\n\n\n");
}